-Name: Send mail
  uses: dawidd6/action-send-mail@v3
  with:
    # Required mail server address if not connection_url:
    server_address: smtp.gmail.com
    # Server port, default 25:
    server_port: 465
    # Optional whether this connection use TLS (default is true if server_port is 465)
    secure: true
    # Required mail subject:
    subject: Github Actions job result
    # Required recipients' addresses:
    to: amaffei1@babson.edu,  jrussoalvesdelima1@babson.edu
    # Required sender full name (address can be skipped):
    from: amaffei1@babson.edu # <user@example.com>
    # Optional plain body:
    body: Build job of ${{github.repository}} completed successfully!
    # Optional priority: 'high', 'normal' (default) or 'low'
    priority: low
